country: china
province: beijing
city: beijing
area: haidian

server:
  port: 80

user:
  name: czt
  age: 22

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 19

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 19

user3: [{name: zhangsan,age: 18},{name: lisi,age: 19}]

#使用${属性名}引用数据
app: ${user.name}\t cool

#使用双引号可以识别转义字符
app2: "${user.name}\t cool"


# 创建类，用于封装下面的数据
# 由Spring加载数据到对象中，一定要告诉spring加载这组数据
# 使用时从Spring中直接获取信息使用

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: 123456