server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC
      username: root
      password: 123456

# \u8BBE\u7F6Eid\u81EA\u589E
mybatis-plus:
  global-config:
    db-config:
      id-type: auto


  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl